### PR TITLE
Dialogue Addition

### PR DESCRIPTION
**Pull request by TikkuTokku**
Regression Dialogue Folder was added. It has a manifest that uses Content Patcher

The content.JSON tells Content Patcher to look in the Dialogue folder for changes.

When talking to Vincent or Jas for the first time, the player will get a question about whether or not they'd want ABDL lines for them. If they choose no, all ABDL changes for them will be replaced with normal dialogue. This includes reactions to the player using their pants.

Jodi has full dialogue for every day of the year.

Vincent has full dialogue for every day of the year.

Sebastion has one ABDL question for when I was learning how to do that.

Jas has the introduction question.

en.JSON was edited to have less humilation, Jodi reactions, and Vincent reactions only if the introduction question answered yes.

### CODE REVIEW

**Comment by zippity21** [comment]
Is the content package ever intended to be released outside of this mod? 

If so, then this is perhaps best implemented as its own repository, so that it's release is not necessarily tied to this mod (though it is a great supplement). Or if you want to divorce it from this mod's release cycle, but still want to have them tied together, you can update your "ContentPackedFor" field.

If not, we should to merge into a single manifest file so that the releases _are_ tied together. Additionally, we would want to include the relevant files into the Solution, so that the content is packaged with a release. (instead of the player having to manage it as two separate mods.) And, given that we are specifically targeting v1.5.5, we'd want to change the Content Patcher version to 1.24.4-beta.20211112.

The advantage of keeping them together is that it gives us the possibility of implementing custom tokens that relate to the regression mod itself (state of underwear, continence levels, etc.) Also, there would only be one mod to update, instead of both the mod and content package.

The advantage of separating them is that it does not force a dependency on the user. So they could theoretically use your package without installing this mod.

Either way, it looks good! Let's just resolve this question before doing a pull.

**Comment by TikkuTokku** [comment]
Thanks for the comment.

I'm not personally intending to release this as a separate mod. I tried to work my content into the original manifest, but it gave me an error saying that it could either be for PyTK or ContentPatcher, but not both. So there needs to be a separate manifest for ContentPatcher to look for. In my mod folder I currently have it set up as one mod folder that contains the regression folder for PyTK and the regression dialogue folder for ContentPatcher, so it still acts as one mod. 

I think the advantages of tying them together outweighs the advantages of keeping them separate, though, I'm partial to doing whatever happens to be easiest.

**Comment by TikkuTokku** [comment]
I'm about half way through writing Sam. It might be a good idea to hold off on this pull request so I can add Sam's dialogue and make a new pull request with it.

Also, I made my manifest before I ever considered working with you on adding dialogue to this mod. I was using a tutorial and making up names just to move on to the actual modding part. I can change it so the name, version, unique ID, and all that match the regression mod.

**Comment by zippity21** [comment]
To be honest I've been looking into how to best deal with this, so the delay is probably a good thing.

Apparently, content packs are treated as separate mods and there doesn't seem to be any easy way to include them in the release. Unfortunately there is only limited control on how the zip is packaged, and I haven't been able to make it work within this mod's directory via making it a "temporary content pack". (There may be a way to do it, but I've been stumped the past few days.)

So I see two options:
1) release it as part of this mod, but require the user to move the content pack up a directory. Or

2) Make it a separate release.

Either way, the manifest of both need to be updated to be mutually dependent. (I.e. the content pack needs to be "packedfor" this mod, and this mod needs to be dependent on the content pack.

Thoughts?

**Comment by TikkuTokku** [comment]
Either I have a solution or I don't understand the problem.

My set up currently looks like this:
-In my mod folder for Stardew Valley I have the folder "Regression 1.2.2"
-In "Regression 1.2.2" I have two folders, "Regression" and "Regression Dialogue"
-Those two folders contain their own manifests and codes and act as their own separate mods.

"Regression" and "Regression Dialogue" are both easily located by Smapi as their own mods despite being located in the same folder, and they run just fine together without the dependencies you mentioned. I tried Zipping "Regression 1.2.2" with both folders and it did that just fine too.

**Comment by zippity21** [comment]
I think your solution y fine, and is how I expected it to work. However, it wasn't on my end.

I think I need to cleanup and try again, because that would be so much cleaner if it works. (And it would mean I wasted a whole bunch of time, sigh...)

The only other thing is that I'd want you to fix the spelling of "supliment" to "supplement"

**Comment by TikkuTokku** [comment]
Gah! I doubt that's going to be the only embarrassing spelling mistake. 

While working on Sam, I did notice one other thing I'd like to fix. I should be done with him today or tomorrow. Let's cancel this pull request while I clean a couple things up and then I'll submit a new one.

**Pull request closed without merging**
